-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 03:54:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema techstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techstore` DEFAULT CHARACTER SET utf8mb4 ;
USE `techstore` ;

-- -----------------------------------------------------
-- Table `techstore`.`categoría`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`categoría` (
  `ID_Categoría` INT(11) NOT NULL,
  `Nombre` VARCHAR(25) NULL DEFAULT NULL,
  `Descripción` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Categoría`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`clientes` (
  `ID_Cliente` INT(11) NOT NULL,
  `TipoCliente` VARCHAR(25) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Tipo_Ide` VARCHAR(25) NOT NULL,
  `Num_Ide` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`empleados` (
  `ID_Empleado` INT(11) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `Rol` VARCHAR(25) NOT NULL,
  `Teléfono` VARCHAR(25) NULL DEFAULT NULL,
  `user` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`proveedor` (
  `ID_Proveedor` INT(11) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `RUC` DECIMAL(11,0) NOT NULL,
  `Razon_Social` VARCHAR(50) NOT NULL,
  `Dirección` VARCHAR(100) NULL DEFAULT NULL,
  `Teléfono` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`producto` (
  `ID_Producto` INT(11) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `Stock` INT(11) NULL DEFAULT NULL,
  `ID_Proveedor` INT(11) NOT NULL,
  `ID_Categoría` INT(11) NOT NULL,
  PRIMARY KEY (`ID_Producto`),
  INDEX `R_37` (`ID_Proveedor` ASC) VISIBLE,
  INDEX `R_44` (`ID_Categoría` ASC) VISIBLE,
  CONSTRAINT `R_37`
    FOREIGN KEY (`ID_Proveedor`)
    REFERENCES `techstore`.`proveedor` (`ID_Proveedor`),
  CONSTRAINT `R_44`
    FOREIGN KEY (`ID_Categoría`)
    REFERENCES `techstore`.`categoría` (`ID_Categoría`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`ventas` (
  `ID_Ventas` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_Cliente` INT(11) NOT NULL,
  `ID_Empleado` INT(11) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Monto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID_Ventas`),
  INDEX `R_31` (`ID_Empleado` ASC) VISIBLE,
  INDEX `R_42` (`ID_Cliente` ASC) VISIBLE,
  CONSTRAINT `R_31`
    FOREIGN KEY (`ID_Empleado`)
    REFERENCES `techstore`.`empleados` (`ID_Empleado`),
  CONSTRAINT `R_42`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `techstore`.`clientes` (`ID_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techstore`.`ventasdetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`ventasdetalle` (
  `ID_VentaDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_Ventas` INT(11) NOT NULL,
  `ID_Producto` INT(11) NULL DEFAULT NULL,
  `Cantidad` DECIMAL(10,0) NOT NULL,
  `Precio_Venta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID_VentaDetalle`),
  INDEX `R_36` (`ID_Producto` ASC) VISIBLE,
  INDEX `FK_VentasDetalle_Ventas` (`ID_Ventas` ASC) VISIBLE,
  CONSTRAINT `FK_VentasDetalle_Ventas`
    FOREIGN KEY (`ID_Ventas`)
    REFERENCES `techstore`.`ventas` (`ID_Ventas`),
  CONSTRAINT `R_36`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `techstore`.`producto` (`ID_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `techstore` ;

-- -----------------------------------------------------
-- procedure ClientexID
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ClientexID`(
IN codcl int (11))
SELECT  *  FROM CLIENTES
WHERE ID_CLIENTE = codcl$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ProductoxID
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProductoxID`(
IN codpr int (11))
SELECT  *  FROM producto
WHERE ID_Producto = codpr$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPAgregarCategorias
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPAgregarCategorias`(
IN	ID_CATEGORIA 	int(11),
IN 	Nombre			varchar(25),
IN 	Descripcion		varchar(100)
)
INSERT INTO categoría values(ID_Categoría,Nombre,Descripción)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPAgregarCliente
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPAgregarCliente`(
IN	ID_Cliente	int(11),
IN	TipoCliente	varchar(25),	
IN	Nombre		varchar(25),
IN	Tipo_Ide	varchar(25),	
IN	Num_Ide		varchar(25)	
)
INSERT INTO clientes values (ID_Cliente,TipoCliente,Nombre,Tipo_Ide,Num_Ide)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPAgregarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPAgregarProducto`(
IN ID_Producto	int(11),
IN Nombre	varchar(25),
IN Precio	decimal(10,2),
IN Stock	int(11),
IN ID_Proveedor	int(11),
IN ID_Categoría	int(11)
)
INSERT INTO producto values(ID_Producto,Nombre,precio,stock,ID_Proveedor,ID_Categoría)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPAgregarProveedor
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPAgregarProveedor`(
IN	ID_Proveedor	int(11),
IN	Nombre	varchar(50),
IN	RUC	decimal(11,0),
IN	Razon_Social	varchar(50),
IN	Dirección	varchar(100),
IN	Teléfono	varchar(25)
)
INSERT INTO proveedor values (ID_Proveedor, Nombre, RUC, Razon_Social, Dirección, Teléfono)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEditarCategoria
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEditarCategoria`(
	IN	codigoCategoria int(11),
	IN 	nombre1			varchar(25),
	IN 	descripcion1	varchar(100)
)
UPDATE categoría
SET Nombre		=  	nombre1,
	Descripción	=	descripcion1
where ID_Categoría = codigoCategoria$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEditarCliente
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEditarCliente`(
	IN	codigoCliente 	int(11),
	IN 	tipoCliente1	varchar(25),
	IN 	nombre1			varchar(25),
	IN 	tipoDocumento 	varchar(25),
	IN 	numeroDocumento	varchar(25)
)
UPDATE CLIENTES
SET TipoCliente =  	tipoCliente1,
	Nombre		=  	nombre1,
	Tipo_Ide	=	tipoDocumento,
	Num_Ide		=	numeroDocumento
where ID_Cliente = 	codigoCliente$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEditarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEditarProducto`(
	IN	codigoProducto 	int(11),
	IN 	nombre1			varchar(25),
	IN 	Precio1			decimal(10,2),
	IN 	Stock1			int(11),
	IN 	ID_Proveedor1	int(11),
	IN 	ID_Categoría1	int(11)
)
UPDATE 	producto
SET 	
		Nombre			=	nombre1,
		Precio			=	Precio1,	
		Stock			=	Stock1,		
		ID_Proveedor	=	ID_Proveedor1,
		ID_Categoría	=	ID_Categoría1
where	ID_Producto = codigoProducto$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEditarProveedor
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEditarProveedor`(
	IN	codigoProveedor int(11),
	IN 	nombre1	 varchar(50),
	IN	RUC1		decimal(11,0),
	IN	Razon_Social1	varchar(50),
	IN	Dirección1	varchar(100),
	IN	Teléfono1	varchar(25)
)
UPDATE proveedor
SET Nombre		=  	nombre1,
	RUC	= RUC1,
	Razon_Social = Razon_Social1,
	Dirección = Dirección1,
	Teléfono = Teléfono1
where ID_Proveedor = codigoProveedor$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEliminarCategoria
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEliminarCategoria`(IN codigoCategoria int(11))
DELETE FROM categoría where ID_Categoría = codigoCategoria$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEliminarCliente
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEliminarCliente`(IN codigoCliente int(11))
DELETE FROM clientes where ID_Cliente = codigoCliente$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEliminarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEliminarProducto`(IN codigoProducto int(11))
DELETE FROM producto where ID_Producto = codigoProducto$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPEliminarProveedor
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPEliminarProveedor`(IN codigoProveedor int(11))
DELETE FROM proveedor where ID_Proveedor = codigoProveedor$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPInsertarVenta
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPInsertarVenta`(
IN	ID_Cliente 	int(11),
IN 	ID_Empleado	int(11),
IN 	Fecha		date,
IN 	Monto		decimal(10,2)
)
INSERT INTO ventas values(ID_Cliente ,ID_Empleado,Fecha,Monto)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPListarCategorias
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPListarCategorias`()
SELECT * FROM categoría$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPListarClientes
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPListarClientes`()
select * from clientes$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPListarProductos
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPListarProductos`()
SELECT * FROM producto$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPListarProveedores
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPListarProveedores`()
select * from proveedor$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure USPVentasDetalle
-- -----------------------------------------------------

DELIMITER $$
USE `techstore`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `USPVentasDetalle`(
IN 	ID_Ventas		int(11),
IN	ID_Producto		int(11),
IN	Cantidad		decimal(10),
IN	Precio_Venta	decimal(10,2)
)
INSERT INTO ventasdetalle values (ID_Ventas,ID_Producto,Cantidad,Precio_Venta)$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
